package br.com.sevencode.android.feia2014.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import br.com.sevencode.android.feia2014.db.Event;
import br.com.sevencode.android.feia2014.db.MyEvent;

import br.com.sevencode.android.feia2014.db.EventDao;
import br.com.sevencode.android.feia2014.db.MyEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig myEventDaoConfig;

    private final EventDao eventDao;
    private final MyEventDao myEventDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        myEventDaoConfig = daoConfigMap.get(MyEventDao.class).clone();
        myEventDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        myEventDao = new MyEventDao(myEventDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(MyEvent.class, myEventDao);
    }
    
    public void clear() {
        eventDaoConfig.getIdentityScope().clear();
        myEventDaoConfig.getIdentityScope().clear();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public MyEventDao getMyEventDao() {
        return myEventDao;
    }

}
