package br.com.sevencode.android.feia2014.db;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EVENT.
 */
public class Event implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 2189779190185916804L;
	
	private Long id;
    private Integer eventId;
    private Integer duration;
    private String name;
    private String author;
    private Integer type;
    private Integer category;
    private java.util.Date date;
    private String dateArray;
    private String placeData;
    private String description;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, Integer eventId, Integer duration, String name, String author, Integer type, Integer category, java.util.Date date, String dateArray, String placeData, String description) {
        this.id = id;
        this.eventId = eventId;
        this.duration = duration;
        this.name = name;
        this.author = author;
        this.type = type;
        this.category = category;
        this.date = date;
        this.dateArray = dateArray;
        this.placeData = placeData;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getEventId() {
        return eventId;
    }

    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getDateArray() {
        return dateArray;
    }

    public void setDateArray(String dateArray) {
        this.dateArray = dateArray;
    }

    public String getPlaceData() {
        return placeData;
    }

    public void setPlaceData(String placeData) {
        this.placeData = placeData;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
